- name: Backup existing Zabbix agent configuration
  copy:
    src: /etc/zabbix/zabbix_agent2.conf
    dest: /etc/zabbix/zabbix_agent2.conf.bak
    remote_src: true
  when: ansible_facts['os_family'] == 'RedHat' and ansible_facts['distribution_major_version']|int >= 7
  ignore_errors: true

- name: Deploy Zabbix agent configuration
  template:
    src: misc/zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Zabbix Agent

